server:
  port: 8080

spring:
  application:
    name: cloud-payment-service
  redis:
    host: 47.108.77.176
    port: 80
    password: redis123456
#    host: 127.0.0.1
#    port: 6379
#    password: 123456
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
    #虚拟host 可以不设置,使用server默认host
    virtual-host: JCcccHost

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.108.77.176:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zgs.test.web_demo.entity
